/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PRIMEFIB_H_RPCGEN
#define _PRIMEFIB_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct pf_result {
	int num;
	int time;
};
typedef struct pf_result pf_result;

#define primefib_PROG 0x23456789
#define primefib_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define prime 1
extern  pf_result * prime_1(int *, CLIENT *);
extern  pf_result * prime_1_svc(int *, struct svc_req *);
#define fib 2
extern  pf_result * fib_1(int *, CLIENT *);
extern  pf_result * fib_1_svc(int *, struct svc_req *);
extern int primefib_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define prime 1
extern  pf_result * prime_1();
extern  pf_result * prime_1_svc();
#define fib 2
extern  pf_result * fib_1();
extern  pf_result * fib_1_svc();
extern int primefib_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_pf_result (XDR *, pf_result*);

#else /* K&R C */
extern bool_t xdr_pf_result ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PRIMEFIB_H_RPCGEN */
