//********************************************************************
//
// Xinyi Wang
// Advanced Operating Systems
// Programming Project #2: Programming using MPI and RPC
// Project 2_2: the client/server model
// Date Assigned: Thursday, March 7, 2013
// Due Date: Tuesday, March 26, 2013 by 9:30 a.m. 
// Instructor: Dr. Ajay K. Katangur
//
//********************************************************************

/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "primefib.h"
#include <sys/types.h>
#include <sys/time.h>
#include <time.h>
#include <stdio.h>
#include <stdlib.h>



//********************************************************************
//
// Prime and Fibonacci Function
//
// This function connects a client stub to a host based on the ip address 
// using UDP. It gets the returned result by using the prime_1 function and 
// the fibonacci_1 function, and the time taken by the server for computation.
//
//
// Return Value
// ------------
// void  
//                      
//
// Value Parameters
// ----------------
// host		char*						server_host
// number	int			                num-th number for input
//
//
// Reference Parameters
// --------------------
// None
//
//
// Local Variables
// ----------------
// clnt				CLIENT*                the client
// result_1			pf_result*		       the returned value from function prime_1
// prime_1_arg		int					   the num-th prime number
// result_2  		pf_result*		       the returned value from function fib_1
// fib_1_arg		int					   the num-th fibonacci number
// t1				struct timeval		   record start time for calculate prime num
// t2				struct timeval		   record end time for calculate prime num
// t3				struct timeval		   record start time for calculate fib num
// t4				struct timeval		   record end time for calculate fib num
//
//*******************************************************************

void
primefib_prog_1(char *host, int number)
{
	CLIENT *clnt;
	pf_result  *result_1;
	int  prime_1_arg;
	pf_result  *result_2;
	int  fib_1_arg;
	
	prime_1_arg = number;
	fib_1_arg = number;
	
	struct timeval t1,t2,t3,t4;
	
#ifndef	DEBUG
	clnt = clnt_create (host, primefib_PROG, primefib_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	
	gettimeofday(&t1,NULL);
	result_1 = prime_1(&prime_1_arg, clnt);
	gettimeofday(&t2,NULL);
	
	result_1->time = (t2.tv_sec-t1.tv_sec)*1000000+(t2.tv_usec-t1.tv_usec);
	
	if (result_1 == (pf_result *) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
			printf("Prime number %d is %d and the time taken is %d micro seconds. \n", prime_1_arg, result_1->num, result_1->time);
		}
		
	gettimeofday(&t3,NULL);
	result_2 = fib_1(&fib_1_arg, clnt);
	gettimeofday(&t4,NULL);
	
	result_2->time = (t4.tv_sec-t3.tv_sec)*1000000+(t4.tv_usec-t3.tv_usec);
	
	if (result_2 == (pf_result *) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
			printf("Fibonacci number %d is %d and the time taken is %d micro seconds. \n", fib_1_arg, result_2->num, result_2->time);
		}
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}



//*************************************************************************
//
// main Function
// -------------
// This function is the client side function, and get the returned result 
// and the time taken by the server for computation. Finally, it will print out 
// the information to the client's screen.
// 
//
// Return Value
// ------------
// int                         0 if program works good                     
//
//
// Value Parameters
// ----------------
// argc		int    		   				count of command                            
// argv     character array pointer  	content of command   
//            
//
// Reference Parameters
// -------------------- 
// None    
//
//
// Local Variables
// ---------------
// host      		char*              		server_host
// number     		int              		num-th number
//
//************************************************************************

int
main (int argc, char *argv[])
{
	char *host;
	int number;
	
	if (argc != 3) {
			printf ("usage: %s server_host number-th \n", argv[0]);
			exit(1);
        }
		
	host = argv[1];
	
	if ((number = atoi(argv[2])) <= 0) {
			fprintf(stderr, "invalid value: %s\n", argv[2]);
			exit(1);
        }
	
	primefib_prog_1 (host, number);
	
	exit (0);
}
