/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "primefib.h"

bool_t
xdr_pf_result (XDR *xdrs, pf_result *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->num))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->time))
		 return FALSE;
	return TRUE;
}
