/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ADD_H_RPCGEN
#define _ADD_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Prime_Fibonacci {
	int a;
	int b;
};
typedef struct Prime_Fibonacci Prime_Fibonacci;

#define ADD_PROG 0x23456789
#define ADD_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ADD 1
extern  int * add_1(Prime_Fibonacci *, CLIENT *);
extern  int * add_1_svc(Prime_Fibonacci *, struct svc_req *);
extern int add_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADD 1
extern  int * add_1();
extern  int * add_1_svc();
extern int add_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Prime_Fibonacci (XDR *, Prime_Fibonacci*);

#else /* K&R C */
extern bool_t xdr_Prime_Fibonacci ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ADD_H_RPCGEN */
